making_a_blog/Blog/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Blog.Data.FileManager;
using Blog.Data.Repository;
using Blog.Models;
using Blog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public PanelController(
            IRepository repo,
            IFileManager fileManager
            )
        {
            _repo = repo;
            _fileManager = fileManager;

        }
        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new PostViewModel());
            }
            else
            {
                var post = _repo.GetPost((int)id);
                return View(new PostViewModel
                {
                    Id = post.Id,
                    Title = post.Title,
                    Body = post.Body,
                    CurrentImage = post.Image,
                    Description = post.Description,
                    Category = post.Category,
                    Tags = post.Tags
                });
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Description = vm.Description,
                Category = vm.Category,
                Tags = vm.Tags
            };

            if (vm.Image == null)
                post.Image = vm.CurrentImage;
            else
            {
                if (!string.IsNullOrEmpty(vm.CurrentImage))
                    _fileManager.RemoveImage(vm.CurrentImage);

                post.Image = await _fileManager.SaveImage(vm.Image);
            }

            if (post.Id > 0)
                _repo.UpdatePost(post);
            else
                _repo.AddPost(post);

            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index");
            else
                return View(post);
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

making_a_blog/Blog/Views/Panel/Edit.cshtml
@model PostViewModel

@{ 

}
<link href="~/lib/Trumbowyg-master/dist/ui/trumbowyg.min.css" rel="stylesheet" />
<div>
    <form asp-controller="Panel" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <div>
            <lable>Title</lable>
            <input asp-for="Title" />
        </div>
        <div>
            <lable>Description</lable>
            <input asp-for="Description" />
        </div>
        <div>
            <lable>Tags</lable>
            <input asp-for="Tags" />
        </div>
        <div>
            <lable>Category</lable>
            <select asp-for="Category">
                <option value="Travel">Travel</option>
                <option value="Programing">Programing</option>
                <option value="Photography">Photography</option>
            </select>
        </div>
        <div>
            <lable>Body</lable>
            <textarea id="editor" asp-for="Body"></textarea>
        </div>
        <div>
            <lable>Image</lable>
            <input asp-for="CurrentImage" type="hidden" />
            <input asp-for="Image" />
        </div>
        <input type="submit" value="submit" />
    </form>
</div>

@section scripts {
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/Trumbowyg-master/dist/trumbowyg.min.js"></script>
    <script>
        $('#editor').trumbowyg();

        // . - class
        // # - id
        // nav - html element
    </script>
}

making_a_blog/Blog/Views/Panel/Index.cshtml
@model IEnumerable<Post>

@{ 

}

<h2>Admin Panel!</h2>
<a asp-controller="Panel" asp-action="Edit">
    Add New Post
</a>

<div>
    <ul>
        @foreach(var post in Model)
        {
        <li>
                @post.Title
            -
            <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.Id">
                Edit
            </a>
            -
            <a asp-controller="Panel" asp-action="Remove" asp-route-id="@post.Id">
                Remove
            </a>
        </li>
        }
    </ul>
</div>